import RPi.GPIO as GPIO

RPI_TO_ARDUINO_PIN_LED_ONE = 3
RPI_TO_ARDUINO_PIN_LED_TWO = 4
ARDUINO_TO_RPI_PIN = 2

GPIO.setmode(GPIO.BCM)
GPIO.setup(RPI_TO_ARDUINO_PIN_LED_ONE, GPIO.OUT)
GPIO.setup(RPI_TO_ARDUINO_PIN_LED_TWO, GPIO.OUT)
GPIO.setup(ARDUINO_TO_RPI_PIN, GPIO.IN)

try:
    while True:
        if GPIO.input(ARDUINO_TO_RPI_PIN) == GPIO.HIGH:
            GPIO.output(RPI_TO_ARDUINO_PIN_LED_ONE, GPIO.HIGH) if RPI_TO_ARDUINO_PIN_LED_ONE == GPIO.LOW else GPIO.output(RPI_TO_ARDUINO_PIN_LED_ONE, GPIO.LOW)
            GPIO.output(RPI_TO_ARDUINO_PIN_LED_TWO, GPIO.LOW) if RPI_TO_ARDUINO_PIN_LED_TWO == GPIO.HIGH else GPIO.output(RPI_TO_ARDUINO_PIN_LED_TWO, GPIO.HIGH)
finally:
    GPIO.cleanup()
